language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

cache:
  - pip
  - apt

before_install:
  - sudo wget -O - https://nightly.odoo.com/odoo.key -nv | apt-key add -
  - sudo echo "deb http://nightly.odoo.com/8.0/nightly/deb/ ./" >> /etc/apt/sources.list.d/odoo.list
  - sudo apt-get update && apt-get install -y odoo
install:
  - travis_retry pip install -r requirements.txt
  - python setup.py develop
script:
  - pwd -P
  - oerpscenario/openerp_scenario.py -k -t auto_test --server-args="--config=$TRAVIS_BUILD_DIR/oerpscenario/test/config/odoo.conf"
  - (/usr/bin/odoo.py --config="$TRAVIS_BUILD_DIR/oerpscenario/test/config/odoo.conf" &)
  - sleep 2
  - oerpscenario/openerp_scenario.py -k -t auto_test_remote --server-config "$TRAVIS_BUILD_DIR/oerpscenario/test/config/oerpscenario.conf"
